
apiVersion: v1
kind: Pod
metadata:
  name: adapted-pod
spec:
  containers:
  - name: app
    image: alpine:3.9.2
    command: ["/bin/sh", "-c"]
    args:
    - while true; do 
        date > /metrics/raw.txt;
        top -n 1 -b >> /metrics/raw.txt;
        sleep 5;
      done
    # Share metric data between containers
    volumeMounts:
    - name: metrics
      mountPath: /metrics
  - name: adapter
    image: alpine:3.9.2
    command: ["/bin/sh", "-c"]
    # Adapt the legacy output to standard monitoring format
    args:
    - while true; do 
        cat /metrics/raw.txt | head -1 > /metrics/adapted.txt;
        cat /metrics/raw.txt | head -2 | tail -1 | grep -o -E '\\d+\\w' | head -1 >> /metrics/adapted.txt;
        cat /metrics/raw.txt | head -3 | tail -1 | grep -o -E '\\d+%' | head -1 >> /metrics/adapted.txt;
        sleep 5;
      done
    # Share metric data between containers
    volumeMounts:
    - name: metrics
      mountPath: /metrics
  volumes:
  - name: metrics
    emptydir: